prefix = (
    "You are a text structuring expert. Please organize the following long text into a well-structured format with a clear hierarchy, ensuring that absolutely no original information is lost.Preserving all details, including characters, events, timelines, and other elements from the original text, is the most fundamental requirement.Try to ensure that the text is divided into no more than 5 sections, while also making sure each section contains at least 1,000 words.:\n"
    "1. **Overall Analysis:**\n"
    "Create a primary title that accurately reflects the main theme of the text (within 15 words);\n"
    "Extract 3-5 core keywords (sorted by importance and separated by semicolons);\n"
    "Summarize the main content in one sentence (within 100 words).\n"
    "\n"
    "2. **Hierarchy Rules:**\n"
    "- **Secondary Titles (within 15 words):**\n"
    "  - Used to distinguish different thematic modules or stages of content;\n"
    "  - Should include 3-5 keywords (separated by semicolons);\n"
    "  - Accompanied by a brief summary (within 100 words);\n"
    "  - If no lower-level titles are present, the original text must be fully retained.\n"
    "- **Tertiary Titles (within 15 words):**\n"
    "  - Used to refine specific content under secondary titles;\n"
    "  - … (Other requirements are the same as for secondary titles).\n"
    "\n"
    "3. **Structure Constraints:**\n"
    "- Ensure that all the original text in your output is completely consistent with the original content, meaning no information from the original text can be omitted.\n"
    "- Referring to the given output format, be sure to indicate the subordination of multilevel headings with numeric labels (like these: 1.; 1.1.; 1.1.1; 1.1.1.1.; 2.; 2.1.; 2.1.1.; 2.1.1.1.). It is only necessary to precede the headings at each level with the above numerical symbols; it is not necessary to use such symbols before the key words and main elements at each level. In doing so, we aim to distinguish the hierarchical structure of the article;\n"
    "- Support up to four hierarchical levels;\n"
    "- It is recommended to divide the text into no more than 5 main sections to ensure clarity and readability.\n"
    "- Title wording should be concise, avoiding questions;\n"
    "- Titles in parallel relationships should maintain consistent grammatical structure.\n"
    "- Be sure to observe: output the original text content only if there are no lower levels after it;\n"
    "\n"
    "**Special Notes:**\n"
    "- All original text must be exactly the same as the corresponding parts in the original document, and all original text combined should encompass all the information in the source text;\n"
    "- Logical relationships between titles at all levels must be clear, avoiding overlapping or redundant content;\n"
    "- Keywords should prioritize the most critical terms expressing the theme of the current level.\n"
    "especially node: The total number of headings must not exceed 5.\n"
    "The word count of the separated original text should be between 500 and 1000 (the text should not be divided too finely).\n"
    "**Please strictly follow the format below for output(Especially for each title, it should start and end with ***.):**\n"
    "Please just return the structured text without any prefix or explanation.\n"
    "***[General Title]***\n"
    "**Keywords**: [Keyword1; Keyword2; Keyword3; Keyword4; Keyword5]\n"
    "**Summary**: [Summary Content]\n"
    "\n"
    "***1. [First Title]***\n"
    "**Keywords**: [Keyword1; Keyword2; Keyword3; Keyword4; Keyword5]\n"
    "**Summary**: [Summary Content]\n"
    "**Original Text**: [If no lower-level titles, include the original text]\n"
    "\n"
    "***1.1 [Secondary Title]***\n"
    "**Keywords**: [Keyword1; Keyword2; Keyword3; Keyword4; Keyword5]\n"
    "**Summary**: [Summary Content]\n"
    "**Original Text**: [If no lower-level titles, include the original text]\n"
    "\n"
    "***1.1.1 [Tertiary Title]***\n"
    "**Keywords**: [Keyword1; Keyword2; Keyword3; Keyword4; Keyword5]\n"
    "**Summary**: [Summary Content]\n"
    "**Original Text**: [If no lower-level titles, include the original text]\n"
    "\n"
    "***1.1.2 [Tertiary Title]***\n"
    "**Keywords**: [Keyword1; Keyword2; Keyword3; Keyword4; Keyword5]\n"
    "**Summary**: [Summary Content]\n"
    "**Original Text**: [If no lower-level titles, include the original text]\n"
    "\n"
    "***1.2 [Secondary Title]***\n"
    "**Keywords**: [Keyword1; Keyword2; Keyword3; Keyword4; Keyword5]\n"
    "**Summary**: [Summary Content]\n"
    "**Original Text**: [If no lower-level titles, include the original text]\n"
    "\n"
    "***1.2.1 [Tertiary Title]***\n"
    "**Keywords**: [Keyword1; Keyword2; Keyword3; Keyword4; Keyword5]\n"
    "**Summary**: [Summary Content]\n"
    "**Original Text**: [If no lower-level titles, include the original text]\n"
    "\n"
    "***1.3 [Secondary Title]***\n"
    "**Keywords**: [Keyword1; Keyword2; Keyword3; Keyword4; Keyword5]\n"
    "**Summary**: [Summary Content]\n"
    "**Original Text**: [If no lower-level titles, include the original text]\n"
    "\n"
    "***2. [First Title]***\n"
    "**Keywords**: [Keyword1; Keyword2; Keyword3; Keyword4; Keyword5]\n"
    "**Summary**: [Summary Content]\n"
    "**Original Text**: [If no lower-level titles, include the original text]\n"
    "\n"
    "...\n"
    "Please just return the structured text without any prefix or explanation."
    "The text content is: \n"
    )